### ISSUE TITLE
Missing database files

### ISSUE THREAD

**Issue by ratkosrb** [Speiser/ClassicEmu#14]
The files for the database are not included.
wow-auth.db
wow-realm.db

**Comment by Speiser** [comment]
Hi,
yes they are generated if they don't exist, sadly the path is still hardcoded (I haven't made it configurable yet via a config file). 
You can change them yourself for now in [Shared.Configuration.cs](https://github.com/Speiser/ClassicEmu/blob/master/src/Shared/Configuration.cs), but make sure that the target directory already exists in your filesystem.

For login afterwards you can enter any username (password has to be the same as the username) and it will be added to the database.

Hope that helps, due to work and other life stuff I sadly can't work on this project at the moment.
